# Generated by Django 4.1.7 on 2023-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalaakaar_registration', '0002_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
