# Generated by Django 4.1.7 on 2023-03-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalaakaar_registration', '0004_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Bussiness_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Pincode',
            field=models.IntegerField(default=410206),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='choose_a_kalaakaar',
            field=models.CharField(choices=[('CR', 'Choreographer'), ('SR', 'Singer'), ('TA', 'Tatoo Artist'), ('PH', 'Photographer'), ('VH', 'Videographer')], default='1', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
