# Generated by Django 4.1.7 on 2023-03-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalaakaar_registration', '0005_myuser_bussiness_name_myuser_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='choose_a_kalaakaar',
            field=models.CharField(choices=[('SL', 'Select A kalaakaar'), ('CR', 'Choreographer'), ('SR', 'Singer'), ('TA', 'Tatoo Artist'), ('PH', 'Photographer'), ('VH', 'Videographer')], default='SL', max_length=2, null=True),
        ),
    ]
