# Generated by Django 4.1.7 on 2023-03-22 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalaakaar_registration', '0006_alter_myuser_pincode_alter_myuser_choose_a_kalaakaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Pincode',
            field=models.IntegerField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be entered in the format +99999999, Upto 15 digits allowed', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
