# Generated by Django 4.1.7 on 2023-03-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalaakaar_registration', '0007_alter_myuser_pincode_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Pincode',
            field=models.IntegerField(null=True),
        ),
    ]
